/*
 * This is the header file for the misc.cpp file. Constants and
 * function headers for misc.cpp should go here.
 *
 * License: This software is licensed under the GPL. You are
 * free to make any modifications, updates, changes, and distribute
 * this code provided you release all of the source code under the 
 * GPL.
 * 
 * DISCLAIMER: THIS SOFTWARE IS PROVIDED AS IS WITH NO WARRANTIES OR
 * ANY PROMISE TO MAINTAIN DATA INTEGRITY. BY USING THIS SOFTWARE, YOU
 * ACKNOWLEDGE THAT YOU UNDERSTAND THE RISKS INVOLVED AND RELEASE ALL
 * DEVELOPERS, OWNERS, AND ANYONE ASSOCIATION WITH THE DEVELOPMENT OF
 * THIS SOFTWARE FROM ANY LIABILITY.
 */

#ifndef MISC_H
#define MISC_H

//parameter structs
 typedef struct {
 	std::string a_source;
 	std::string a_lang;
 	std::string a_name;
	bool a_verbose;
	bool k_makef;
	std::string comp;
	std::string m_util;
	std::string n_flags;
 } Parameters;
 
 //command line flag constants
 const std::string p_verbose = "-v";
 const std::string src_dir = "-s";
 const std::string p_lang = "-l";
 const std::string exec_name = "-n";
 const std::string help = "-h";
 const std::string k_makef = "-k";
 const std::string comp = "-c";
 const std::string m_util = "-m";
 const std::string n_flags = "-f";
 
 //return codes
 const int STATUS_OK = 0;					//This means everything is OK
 const int STATUS_INVALID_OPT = 1;			//This means given option is not valid
 const int STATUS_INVALID_LANG = 2;			//This means the given language is not recognized
 const int STATUS_MAKEFILE_ERR = 3;			//This means there was a problem generating the makefile
 const int STATUS_STOP = 4;					//This means gently stop the program (not really an error)
 const int STATUS_FILE_IO_ERR = 5;			//This means there was some file input/output error
 const int STATUS_EXEC_MAKEFILE_ERR = 6;	//This means there was a problem executing the makefile

 //programming languages
 const std::string c_lang = "c";
 const std::string cpp_lang_1 = "c++";
 const std::string cpp_lang_2 = "cpp";
 const std::string cpp_lang_3 = "cc";
 const std::string cpp_lang_4 = "cxx";
 const std::string java_lang = "java";
 
 //miscellaneous information about realmake
 const std::string c_version = "2.1";
 const std::string m_header = 
"# This is a makefile generated by the realmake program that includes\n\
# all options to compile and build the code.\n\
#\n\
# License: This software is licensed under the GPL. You are\n\
# free to make any modifications, updates, changes, and distribute\n\
# this code provided you release all of the source code under the\n\
# GPL.\n\
#\n\
# DISCLAIMER: THIS SOFTWARE IS PROVIDED AS IS WITH NO WARRANTIES OR\n\
# ANY PROMISE TO MAINTAIN DATA INTEGRITY. BY USING THIS SOFTWARE, YOU\n\
# ACKNOWLEDGE THAT YOU UNDERSTAND THE RISKS INVOLVED AND RELEASE ALL\n\
# DEVELOPERS, OWNERS, AND ANYONE ASSOCIATION WITH THE DEVELOPMENT OF\n\
# THIS SOFTWARE FROM ANY LIABILITY.";

 //function prototypes
 std::string match_lang(const std::string &lang);
 bool is_empty(const std::string &t_string);
 
 //names of known compilers and make programs
 const std::string make = "make";
 const std::string gmake = "gmake";

#endif
